development: &default
  adapter: postgresql
  encoding: unicode
  database: box_storage_development
  encoding: utf8
  host: localhost
  pool: 5

test: &test
  <<: *default
  database: box_storage_test

production:
  <<: *default
  database: box_storage
